name: Deploy NUC Stack

on:
  push:
    branches: [ main ]

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Frontend via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.NUC_HOST }}
          username: ${{ secrets.NUC_USER }}
          key: ${{ secrets.NUC_SSH_KEY }}
          script: |
            echo "Atualizando frontend..."
            cd /home/alpine/frontend
            git reset --hard HEAD        # garante que alterações locais não atrapalhem
            git clean -fdx               # remove arquivos não rastreados
            git pull origin main

            # Força rebuild completo da imagem, ignorando cache
            docker-compose -f /home/alpine/docker-compose.yml build --no-cache frontend

            # Sobe o container atualizado
            docker-compose -f /home/alpine/docker-compose.yml up -d frontend
            echo "Frontend atualizado!"
